const cityImageUrls = {
  Egypt:
    "https://cdn.enjoytravel.com/img/travel-news/cairo-egypt-with-4-388-million-tourists-per-year.jpg",
  Greece:
    "https://cdn.enjoytravel.com/img/travel-news/athens-greece-with-4-797-million-tourists-per-year.jpg",
  Moscow:
    "https://cdn.enjoytravel.com/img/travel-news/moscow-russia-with-4-800-million-tourists-per-year.jpg",
  Italy:
    "https://cdn.enjoytravel.com/img/travel-news/florence-italy-with-4-941-million-tourists-per-year.jpg",
  Ireland:
    "https://cdn.enjoytravel.com/img/travel-news/dublin-ireland-with-4-986-million-tourists-per-year.jpg",
  Chennai:
    "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q:80&w:1470&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  Orlando:
    "https://images.unsplash.com/photo-1609184889233-eff6dd93def4?q:80&w:1470&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  Madrid:
    "https://cdn.enjoytravel.com/img/travel-news/madrid-spain-with-5-275-million-tourists-per-year.jpg",
  Jaipur:
    "https://cdn.enjoytravel.com/img/travel-news/jaipur-india-with-5-288-million-tourists-per-year.jpg",
  Venice:
    "https://cdn.enjoytravel.com/img/travel-news/venice-italy-with-5-316-million-tourists-per-year.jpg",
  Riyadh:
    "https://cdn.enjoytravel.com/img/travel-news/riyadh-saudi-arabia-with-5-396-million-tourists-per-year-.jpg",
  Vietnam:
    "https://cdn.enjoytravel.com/img/travel-news/ho-chi-minh-city-vietnam-with-5-500-million-tourists-per-year.jpg",
  Johannesburg:
    "https://cdn.enjoytravel.com/img/travel-news/johannesburg-south-africa-with-5-535-million-tourists-per-year.jpg",
  Malaysia:
    "https://cdn.enjoytravel.com/img/travel-news/johor-bahru-malaysia-with-5-571-million-tourists-per-year.jpg",
  Berlin:
    "https://cdn.enjoytravel.com/img/travel-news/berlin-germany-with-5-627-million-tourists-per-year.jpg",
  Mexico:
    "https://cdn.enjoytravel.com/img/travel-news/cancun-mexico-with-6-039-million-tourists-per-year.jpg",
  Austria:
    "https://cdn.enjoytravel.com/img/travel-news/vienna-austria-with-6-067-million-tourists-per-year-.jpg",
  Indonesia:
    "https://cdn.enjoytravel.com/img/travel-news/denpasar-indonesia-with-6-238-million-tourists-per-year.jpg",
  Milan:
    "https://cdn.enjoytravel.com/img/travel-news/milan-italy-with-6-347-million-tourists-per-year-.jpg",
  Barcelona:
    "https://cdn.enjoytravel.com/img/travel-news/barcelona-spain-with-6-530-million-tourists-per-year.jpg",
  Japan:
    "https://cdn.enjoytravel.com/img/travel-news/osaka-japan-with-6-605-million-tourists-per-year.jpg",
  Agra: "https://cdn.enjoytravel.com/img/travel-news/agra-india-with-6-644-million-tourists-per-year.jpg",
  LasVegas:
    "https://cdn.enjoytravel.com/img/travel-news/las-vegas-us-with-6-687-million-tourists-per-year.jpg",
  LosAngeles:
    "https://cdn.enjoytravel.com/img/travel-news/los-angeles-us-with-7-165-million-tourists-per-year.jpg",
  Shanghai:
    "https://cdn.enjoytravel.com/img/travel-news/shanghai-china-with-7-193-million-tourists-per-year.jpg",
  Pattaya:
    "https://cdn.enjoytravel.com/img/travel-news/pattaya-thailand-with-7-426-million-tourists-per-year.jpg",
  Seoul:
    "https://cdn.enjoytravel.com/img/travel-news/seoul-south-korea-with-7-659-million-tourists-per-year-.jpg",
  Amsterdam:
    "https://cdn.enjoytravel.com/img/travel-news/amsterdam-netherlands-with-7-848-million-tourists-per-year.jpg",
  Miami:
    "https://cdn.enjoytravel.com/img/travel-news/miami-us-with-8-075-million-tourists-per-year.jpg",
  Mecca:
    "https://cdn.enjoytravel.com/img/travel-news/mecca-saudi-arabia-with-8-632-million-tourists-per-year.jpg",
  Prague:
    "https://cdn.enjoytravel.com/img/travel-news/prague-czech-republic-with-8-806-million-tourists-per-year.jpg",
  Mumbai:
    "https://cdn.enjoytravel.com/img/travel-news/mumbai-india-with-8-984-million-tourists-per-year.jpg",
  Guangzhou:
    "https://cdn.enjoytravel.com/img/travel-news/guangzhou-china-with-9-004-million-tourists-per-year.jpg",
  Taiwan:
    "https://cdn.enjoytravel.com/img/travel-news/taipei-taiwan-with-9-273-million-tourists-per-year.jpg",
  Turkey:
    "https://cdn.enjoytravel.com/img/travel-news/antalya-turkey-with-9-482-million-tourists-per-year.jpg",
  Rome: "https://cdn.enjoytravel.com/img/travel-news/rome-italy-with-9-531-million-tourists-per-year.jpg",
  Tokyo:
    "https://cdn.enjoytravel.com/img/travel-news/tokyo-japan-with-9-549-million-tourists-per-year.jpg",
  Istanbul:
    "https://cdn.enjoytravel.com/img/travel-news/istanbul-turkey-with-10-730-million-tourists-per-year-.jpg",
  Phuket:
    "https://cdn.enjoytravel.com/img/travel-news/phuket-thailand-with-11-613-million-tourists-per-year.jpg",
  Shenzhen:
    "https://cdn.enjoytravel.com/img/travel-news/shenzhen-china-with-12-075-million-tourists-per-year.jpg",
  KualaLumpur:
    "https://cdn.enjoytravel.com/img/travel-news/kuala-lumpur-malaysia-with-12-843-million-tourists-per-year.jpg",
  NewYork:
    "https://cdn.enjoytravel.com/img/travel-news/new-york-city-us-with-13-100-million-tourists-per-year.jpg",
  Dubai:
    "https://images.unsplash.com/flagged/photo-1559717201-fbb671ff56b7?q:80&w:1471&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  Paris:
    "https://cdn.enjoytravel.com/img/travel-news/paris-france-with-15-834-million-tourists-per-year-.jpg",
  Macau:
    "https://cdn.enjoytravel.com/img/travel-news/macau-china-with-17-337-million-tourists-per-year.jpg",
  Singapore:
    "https://images.unsplash.com/flagged/photo-1562503542-2a1e6f03b16b?q:80&w:1374&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  London:
    "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q:80&w:1470&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  Bangkok:
    "https://images.unsplash.com/photo-1508009603885-50cf7c579365?q:80&w:1350&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  HongKong:
    "https://cdn.enjoytravel.com/img/travel-news/hong-kong-china-with-27-880-million-tourists-per-year.jpg",
  Pune: "https://images.unsplash.com/photo-1553064483-f10fe837615f?q:80&w:1470&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  Delhi:
    "https://images.unsplash.com/photo-1587474260584-136574528ed5?q:80&w:1470&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  Kolkata:
    "https://images.unsplash.com/photo-1571679654681-ba01b9e1e117?q:80&w:1374&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  Bhopal:
    "https://plus.unsplash.com/premium_photo-1697729585263-29ebdcb972ee?q:80&w:1470&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  Goa: "https://images.unsplash.com/photo-1560179406-1c6c60e0dc76?q:80&w:1374&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  Dehadun:
    "https://media.istockphoto.com/id/825268350/photo/hardiwar.jpg?s:1024x1024&w:is&k:20&c:rZOoRRnc39Fv8oR0rRiqR9_hd91CojWqVLNGXxnA67k:",
  Odisha:
    "https://plus.unsplash.com/premium_photo-1694475133441-bbca84f93082?q:80&w:1470&auto:format&fit:crop&ixlib:rb-4.0.3&ixid:M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
};

export default cityImageUrls;
